---
title: "Covid 19 en México"
author: "Murpholinox Peligro"
date: "`r format(Sys.time(), '%d %m %Y')`"
output: pdf_document 
---


```{r, warning=FALSE, message=FALSE}
# Carga los paquetes necesarios.
library(ggplot2)
#library(ggdark) # No necesario si solo se crea el PDF.
library(latex2exp)
library(lubridate)
library(dplyr)
# Configura el directorio de trabajo.
setwd("/home/murphy/Repos/plotcovid19mx")
```

```{bash, warning=FALSE, message=FALSE}
# Descarga datos del European CDC.
wget -O full.csv https://opendata.ecdc.europa.eu/covid19/casedistribution/csv
# Obtiene las líneas correspondientes a México.
grep Mex full.csv > mex.csv
# Solo ocupamos la columna 1 y 6 (fecha y decesos por día).
awk -F "," '{print $1"," $6}' mex.csv > clean.csv
# Añade nombre a las columnas.
echo "fecha,decesos" >> clean.csv
# Revierte los datos en la lista.
tac clean.csv > clean_r.csv
```

```{r}
# Carga los datos limpios a R.
datos <- read.csv("~/Repos/plotcovid19mx/clean_r.csv")
# Cambia el formato de la fecha de d/m/y a y-m-d.
datos$newdate <- lubridate::dmy(datos$fecha)
```

```{r}
# Crea una nueva variable con un nuevo formato para la fecha (a números enteros).
# Esto se hace porque x con formato de fecha impide que el algoritmo para 
# obtener el modelo exponencial llegue a una solución.
xmax <- max(length(datos$fecha))
datos$number <- seq(0,xmax-1)
# Necesitamos los días del brote en México (después del 20-marzo).
smalldf<-datos %>%
  filter(number >= 72) 
# Ordena los datos a usar en un tibble.
x<-smalldf$number
x<-x-71
y<-smalldf$decesos
y2<-y+1
nice<-tibble(x,y)
# Se crean dos data frames, porque el modelo lineal con logaritmos se quiebra
# al tener ceros en y, por eso tenemos y2.
dummy<-tibble(x,y2)
# Guarda datos finales en formato CSV.
write.csv(nice, file="~/Repos/plotcovid19mx/nice.csv")
# Crea una gráfica base.
p <- ggplot(data = nice, aes(x=x, y=y)) + geom_point()
```

```{r}
# Crea modelo lineal con el data frame dummy que contiene y2=y+1.
linm <- lm(log(y2)~x, data = dummy)
# Obtiene los parámetros del modelo lineal.
a1 <- exp(coef(linm)[1])
b1 <- coef(linm)[2]
# Aplica los parámetros del modelo lineal en la creación del modelo exponencial.
expm <-nls(y ~ a * exp(b * x), start = list(a=a1, b=b1), data = nice)
summary(expm)
a2 <- coef(expm)[1]
b2 <- coef(expm)[2]
# Obtiene el número de decesos acumulados
cum <- sum(y)
```

```{r, warning=FALSE, message=FALSE}
# Agrega el ajuste exponencial a la gráfica base,
p2 <- p +
  stat_smooth(method = 'nls', formula = y ~ a * exp(b * x), se=FALSE,
              method.args = list(start = list(a = a2, b =  b2))) +
# la ecuación de la exponencial,
annotate("label", x = 10, y = 150, 
         label = TeX(sprintf("$y = %.2f e ^{%.2fx}$", a2, b2))) +
# una etiqueta para el número de decesos acumulados,
annotate("label", x = 10, y = 200,
         label = TeX(sprintf("Decesos acumulados, %d", cum)))  +
    # los títulos necesarios,
  ylab("Decesos") + xlab("Día") +
  ggtitle("Decesos por Covid-19 en México, a partir del 20 de marzo.")
p2
```
  
